version: 1

formatters:
  standard:
    format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard

  file:
    class: logging.FileHandler
    filename: logs/system.log
    level: DEBUG
    formatter: standard

root:
  level: DEBUG
  handlers: [console, file]